# Generated by Django 5.1.7 on 2025-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Haute')], default=2),
        ),
    ]
